<?php

/**
 * TrackingApi
 * PHP version 8.2.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator).
 *
 * OpenAPI spec version: 5
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Subugoe\CounterClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Query;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Utils;
use Subugoe\CounterClient\ApiException;
use Subugoe\CounterClient\Configuration;
use Subugoe\CounterClient\HeaderSelector;
use Subugoe\CounterClient\ObjectSerializer;

/**
 * TrackingApi Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class TrackingApi
{
    protected ClientInterface $client;

    protected Configuration $config;

    protected HeaderSelector $headerSelector;

    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation getTrackingItem.
     *
     * Retrieves a Tracking resource.
     *
     * @param string $id id (required)
     *
     * @throws ApiException              on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function getTrackingItem(string $id): \Subugoe\CounterClient\Model\Tracking
    {
        list($response) = $this->getTrackingItemWithHttpInfo($id);

        return $response;
    }

    /**
     * Operation getTrackingItemWithHttpInfo.
     *
     * Retrieves a Tracking resource.
     *
     * @param string $id (required)
     *
     * @return array of \Subugoe\CounterClient\Model\Tracking, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws ApiException              on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function getTrackingItemWithHttpInfo(string $id)
    {
        $request = $this->getTrackingItemRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", $e->getCode(), $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null, $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getBody()->getContents() : null);
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $request->getUri()), $statusCode, $response->getHeaders(), $response->getBody());
            }

            $responseBody = $response->getBody();
            if (200 === $statusCode) {
                if ('\Subugoe\CounterClient\Model\Tracking' === '\SplFileObject') {
                    $content = $responseBody; // stream goes to serializer
                } else {
                    $content = $responseBody->getContents();
                }

                return [
                    ObjectSerializer::deserialize($content, '\Subugoe\CounterClient\Model\Tracking', []),
                    $response->getStatusCode(),
                    $response->getHeaders(),
                ];
            }

            $returnType = '\Subugoe\CounterClient\Model\Tracking';
            $responseBody = $response->getBody();
            if ('\SplFileObject' === $returnType) {
                $content = $responseBody; // stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
        } catch (ApiException $e) {
            if (200 === $e->getCode()) {
                $data = ObjectSerializer::deserialize(
                    $e->getResponseBody(),
                    '\Subugoe\CounterClient\Model\Tracking',
                    $e->getResponseHeaders()
                );
                $e->setResponseObject($data);
            }
            throw $e;
        }
    }

    /**
     * Operation getTrackingItemAsync.
     *
     * Retrieves a Tracking resource.
     *
     * @param string $id (required)
     *
     * @throws \InvalidArgumentException
     */
    public function getTrackingItemAsync(string $id): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->getTrackingItemAsyncWithHttpInfo($id)
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation getTrackingItemAsyncWithHttpInfo.
     *
     * Retrieves a Tracking resource.
     *
     * @param string $id (required)
     *
     * @throws \InvalidArgumentException
     */
    public function getTrackingItemAsyncWithHttpInfo(string $id): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = '\Subugoe\CounterClient\Model\Tracking';
        $request = $this->getTrackingItemRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType): array {
                    $responseBody = $response->getBody();
                    if ('\SplFileObject' === $returnType) {
                        $content = $responseBody; // stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), $response->getBody());
                }
            );
    }

    /**
     * Operation postTrackingCollection.
     *
     * Creates a Tracking resource.
     *
     * @param \Subugoe\CounterClient\Model\Tracking $tracking The new Tracking resource (optional)
     *
     * @throws ApiException              on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function postTrackingCollection(?\Subugoe\CounterClient\Model\Tracking $tracking = null): \Subugoe\CounterClient\Model\Tracking
    {
        list($response) = $this->postTrackingCollectionWithHttpInfo($tracking);

        return $response;
    }

    /**
     * Operation postTrackingCollectionWithHttpInfo.
     *
     * Creates a Tracking resource.
     *
     * @param \Subugoe\CounterClient\Model\Tracking $tracking The new Tracking resource (optional)
     *
     * @return array of \Subugoe\CounterClient\Model\Tracking, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws ApiException              on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function postTrackingCollectionWithHttpInfo(?\Subugoe\CounterClient\Model\Tracking $tracking = null)
    {
        $request = $this->postTrackingCollectionRequest($tracking);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", $e->getCode(), $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null, $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getBody()->getContents() : null);
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $request->getUri()), $statusCode, $response->getHeaders(), $response->getBody());
            }

            $responseBody = $response->getBody();
            if (201 === $statusCode) {
                if ('\Subugoe\CounterClient\Model\Tracking' === '\SplFileObject') {
                    $content = $responseBody; // stream goes to serializer
                } else {
                    $content = $responseBody->getContents();
                }

                return [
                    ObjectSerializer::deserialize($content, '\Subugoe\CounterClient\Model\Tracking', []),
                    $response->getStatusCode(),
                    $response->getHeaders(),
                ];
            }

            $returnType = '\Subugoe\CounterClient\Model\Tracking';
            $responseBody = $response->getBody();
            if ('\SplFileObject' === $returnType) {
                $content = $responseBody; // stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
        } catch (ApiException $e) {
            if (201 === $e->getCode()) {
                $data = ObjectSerializer::deserialize(
                    $e->getResponseBody(),
                    '\Subugoe\CounterClient\Model\Tracking',
                    $e->getResponseHeaders()
                );
                $e->setResponseObject($data);
            }
            throw $e;
        }
    }

    /**
     * Operation postTrackingCollectionAsync.
     *
     * Creates a Tracking resource.
     *
     * @param \Subugoe\CounterClient\Model\Tracking $tracking The new Tracking resource (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postTrackingCollectionAsync(?\Subugoe\CounterClient\Model\Tracking $tracking = null): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->postTrackingCollectionAsyncWithHttpInfo($tracking)
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation postTrackingCollectionAsyncWithHttpInfo.
     *
     * Creates a Tracking resource.
     *
     * @param \Subugoe\CounterClient\Model\Tracking $tracking The new Tracking resource (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postTrackingCollectionAsyncWithHttpInfo(?\Subugoe\CounterClient\Model\Tracking $tracking = null): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = '\Subugoe\CounterClient\Model\Tracking';
        $request = $this->postTrackingCollectionRequest($tracking);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType): array {
                    $responseBody = $response->getBody();
                    if ('\SplFileObject' === $returnType) {
                        $content = $responseBody; // stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), $response->getBody());
                }
            );
    }

    /**
     * Create request for operation 'getTrackingItem'.
     *
     * @param string $id (required)
     *
     * @throws \InvalidArgumentException
     */
    protected function getTrackingItemRequest(string $id): Request
    {
        // verify the required parameter 'id' is set
        if (null === $id || (is_array($id) && 0 === count($id))) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling getTrackingItem');
        }

        $resourcePath = '/api/counter/trackings/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if (null !== $id) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/ld+json', 'application/json', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/ld+json', 'application/json', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ('application/json' === $headers['Content-Type']) {
                $httpBody = Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif ([] !== $formParams) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue,
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ('application/json' === $headers['Content-Type']) {
                $httpBody = Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ('' !== $this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = Query::build($queryParams);

        return new Request(
            'GET',
            $this->config->getHost().$resourcePath.('' !== $query && '0' !== $query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create request for operation 'postTrackingCollection'.
     *
     * @param \Subugoe\CounterClient\Model\Tracking $tracking The new Tracking resource (optional)
     *
     * @throws \InvalidArgumentException
     */
    protected function postTrackingCollectionRequest(?\Subugoe\CounterClient\Model\Tracking $tracking = null): Request
    {
        $resourcePath = '/api/counter/trackings';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // body params
        $_tempBody = null;
        if (isset($tracking)) {
            $_tempBody = $tracking;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/ld+json', 'application/json', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/ld+json', 'application/json', 'text/html'],
                ['application/ld+json', 'application/json', 'text/html']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ('application/json' === $headers['Content-Type']) {
                $httpBody = Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif ([] !== $formParams) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue,
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ('application/json' === $headers['Content-Type']) {
                $httpBody = Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ('' !== $this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = Query::build($queryParams);

        return new Request(
            'POST',
            $this->config->getHost().$resourcePath.('' !== $query && '0' !== $query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option.
     *
     * @return array of http client options
     *
     * @throws \RuntimeException on file opening failure
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'ab');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: '.$this->config->getDebugFile());
            }
        }

        return $options;
    }
}
