/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Tracking'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Tracking'));
  } else {
    // Browser globals (root is window)
    if (!root.OpenapiJsClient) {
      root.OpenapiJsClient = {};
    }
    root.OpenapiJsClient.TrackingApi = factory(root.OpenapiJsClient.ApiClient, root.OpenapiJsClient.Tracking);
  }
}(this, function(ApiClient, Tracking) {
  'use strict';

  /**
   * Tracking service.
   * @module api/TrackingApi
   * @version 5
   */

  /**
   * Constructs a new TrackingApi. 
   * @alias module:api/TrackingApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getTrackingItem operation.
     * @callback module:api/TrackingApi~getTrackingItemCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Tracking} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves a Tracking resource.
     * @param {String} id 
     * @param {module:api/TrackingApi~getTrackingItemCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Tracking}
     */
    this.getTrackingItem = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getTrackingItem");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/ld+json', 'application/json', 'text/html'];
      var returnType = Tracking;

      return this.apiClient.callApi(
        '/api/counter/trackings/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the postTrackingCollection operation.
     * @callback module:api/TrackingApi~postTrackingCollectionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Tracking} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a Tracking resource.
     * @param {Object} opts Optional parameters
     * @param {module:model/Tracking} opts.tracking The new Tracking resource
     * @param {module:api/TrackingApi~postTrackingCollectionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Tracking}
     */
    this.postTrackingCollection = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['tracking'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/ld+json', 'application/json', 'text/html'];
      var accepts = ['application/ld+json', 'application/json', 'text/html'];
      var returnType = Tracking;

      return this.apiClient.callApi(
        '/api/counter/trackings', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
