<?php
/**
 * Tracking
 *
 * PHP version 5
 *
 * @category Class
 * @package  Subugoe\CounterClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Subugoe\CounterClient\Model;

use \ArrayAccess;
use \Subugoe\CounterClient\ObjectSerializer;

/**
 * Tracking Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Subugoe\CounterClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Tracking implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Tracking';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'customerId' => 'string',
        'clientIP' => 'string',
        'platform' => 'string',
        'docDatabase' => 'string',
        'trackingEvent' => 'string',
        'documentId' => 'string',
        'parentId' => 'string',
        'documentUrl' => 'string',
        'documentTitle' => 'string',
        'parentTitle' => 'string',
        'chapter' => 'string',
        'author' => 'string',
        'publisher' => 'string',
        'issnPrint' => 'string',
        'issnOnline' => 'string',
        'isbn' => 'string',
        'isan' => 'string',
        'ismn' => 'string',
        'isrc' => 'string',
        'istc' => 'string',
        'doi' => 'string',
        'proprietaryId' => 'string',
        'accessMethod' => 'string',
        'accessType' => 'string',
        'dataType' => 'string',
        'sectionType' => 'string',
        'yop' => 'string',
        'sessionId' => 'string',
        'created' => 'int',
        'trackingDate' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'id' => null,
        'customerId' => null,
        'clientIP' => null,
        'platform' => null,
        'docDatabase' => null,
        'trackingEvent' => null,
        'documentId' => null,
        'parentId' => null,
        'documentUrl' => null,
        'documentTitle' => null,
        'parentTitle' => null,
        'chapter' => null,
        'author' => null,
        'publisher' => null,
        'issnPrint' => null,
        'issnOnline' => null,
        'isbn' => null,
        'isan' => null,
        'ismn' => null,
        'isrc' => null,
        'istc' => null,
        'doi' => null,
        'proprietaryId' => null,
        'accessMethod' => null,
        'accessType' => null,
        'dataType' => null,
        'sectionType' => null,
        'yop' => null,
        'sessionId' => null,
        'created' => null,
        'trackingDate' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'customerId' => 'customerId',
        'clientIP' => 'clientIP',
        'platform' => 'platform',
        'docDatabase' => 'docDatabase',
        'trackingEvent' => 'trackingEvent',
        'documentId' => 'documentId',
        'parentId' => 'parentId',
        'documentUrl' => 'documentUrl',
        'documentTitle' => 'documentTitle',
        'parentTitle' => 'parentTitle',
        'chapter' => 'chapter',
        'author' => 'author',
        'publisher' => 'publisher',
        'issnPrint' => 'issnPrint',
        'issnOnline' => 'issnOnline',
        'isbn' => 'isbn',
        'isan' => 'isan',
        'ismn' => 'ismn',
        'isrc' => 'isrc',
        'istc' => 'istc',
        'doi' => 'doi',
        'proprietaryId' => 'proprietaryId',
        'accessMethod' => 'accessMethod',
        'accessType' => 'accessType',
        'dataType' => 'dataType',
        'sectionType' => 'sectionType',
        'yop' => 'yop',
        'sessionId' => 'sessionId',
        'created' => 'created',
        'trackingDate' => 'trackingDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'customerId' => 'setCustomerId',
        'clientIP' => 'setClientIP',
        'platform' => 'setPlatform',
        'docDatabase' => 'setDocDatabase',
        'trackingEvent' => 'setTrackingEvent',
        'documentId' => 'setDocumentId',
        'parentId' => 'setParentId',
        'documentUrl' => 'setDocumentUrl',
        'documentTitle' => 'setDocumentTitle',
        'parentTitle' => 'setParentTitle',
        'chapter' => 'setChapter',
        'author' => 'setAuthor',
        'publisher' => 'setPublisher',
        'issnPrint' => 'setIssnPrint',
        'issnOnline' => 'setIssnOnline',
        'isbn' => 'setIsbn',
        'isan' => 'setIsan',
        'ismn' => 'setIsmn',
        'isrc' => 'setIsrc',
        'istc' => 'setIstc',
        'doi' => 'setDoi',
        'proprietaryId' => 'setProprietaryId',
        'accessMethod' => 'setAccessMethod',
        'accessType' => 'setAccessType',
        'dataType' => 'setDataType',
        'sectionType' => 'setSectionType',
        'yop' => 'setYop',
        'sessionId' => 'setSessionId',
        'created' => 'setCreated',
        'trackingDate' => 'setTrackingDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'customerId' => 'getCustomerId',
        'clientIP' => 'getClientIP',
        'platform' => 'getPlatform',
        'docDatabase' => 'getDocDatabase',
        'trackingEvent' => 'getTrackingEvent',
        'documentId' => 'getDocumentId',
        'parentId' => 'getParentId',
        'documentUrl' => 'getDocumentUrl',
        'documentTitle' => 'getDocumentTitle',
        'parentTitle' => 'getParentTitle',
        'chapter' => 'getChapter',
        'author' => 'getAuthor',
        'publisher' => 'getPublisher',
        'issnPrint' => 'getIssnPrint',
        'issnOnline' => 'getIssnOnline',
        'isbn' => 'getIsbn',
        'isan' => 'getIsan',
        'ismn' => 'getIsmn',
        'isrc' => 'getIsrc',
        'istc' => 'getIstc',
        'doi' => 'getDoi',
        'proprietaryId' => 'getProprietaryId',
        'accessMethod' => 'getAccessMethod',
        'accessType' => 'getAccessType',
        'dataType' => 'getDataType',
        'sectionType' => 'getSectionType',
        'yop' => 'getYop',
        'sessionId' => 'getSessionId',
        'created' => 'getCreated',
        'trackingDate' => 'getTrackingDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['customerId'] = isset($data['customerId']) ? $data['customerId'] : null;
        $this->container['clientIP'] = isset($data['clientIP']) ? $data['clientIP'] : null;
        $this->container['platform'] = isset($data['platform']) ? $data['platform'] : null;
        $this->container['docDatabase'] = isset($data['docDatabase']) ? $data['docDatabase'] : null;
        $this->container['trackingEvent'] = isset($data['trackingEvent']) ? $data['trackingEvent'] : null;
        $this->container['documentId'] = isset($data['documentId']) ? $data['documentId'] : null;
        $this->container['parentId'] = isset($data['parentId']) ? $data['parentId'] : null;
        $this->container['documentUrl'] = isset($data['documentUrl']) ? $data['documentUrl'] : null;
        $this->container['documentTitle'] = isset($data['documentTitle']) ? $data['documentTitle'] : null;
        $this->container['parentTitle'] = isset($data['parentTitle']) ? $data['parentTitle'] : null;
        $this->container['chapter'] = isset($data['chapter']) ? $data['chapter'] : null;
        $this->container['author'] = isset($data['author']) ? $data['author'] : null;
        $this->container['publisher'] = isset($data['publisher']) ? $data['publisher'] : null;
        $this->container['issnPrint'] = isset($data['issnPrint']) ? $data['issnPrint'] : null;
        $this->container['issnOnline'] = isset($data['issnOnline']) ? $data['issnOnline'] : null;
        $this->container['isbn'] = isset($data['isbn']) ? $data['isbn'] : null;
        $this->container['isan'] = isset($data['isan']) ? $data['isan'] : null;
        $this->container['ismn'] = isset($data['ismn']) ? $data['ismn'] : null;
        $this->container['isrc'] = isset($data['isrc']) ? $data['isrc'] : null;
        $this->container['istc'] = isset($data['istc']) ? $data['istc'] : null;
        $this->container['doi'] = isset($data['doi']) ? $data['doi'] : null;
        $this->container['proprietaryId'] = isset($data['proprietaryId']) ? $data['proprietaryId'] : null;
        $this->container['accessMethod'] = isset($data['accessMethod']) ? $data['accessMethod'] : null;
        $this->container['accessType'] = isset($data['accessType']) ? $data['accessType'] : null;
        $this->container['dataType'] = isset($data['dataType']) ? $data['dataType'] : null;
        $this->container['sectionType'] = isset($data['sectionType']) ? $data['sectionType'] : null;
        $this->container['yop'] = isset($data['yop']) ? $data['yop'] : null;
        $this->container['sessionId'] = isset($data['sessionId']) ? $data['sessionId'] : null;
        $this->container['created'] = isset($data['created']) ? $data['created'] : null;
        $this->container['trackingDate'] = isset($data['trackingDate']) ? $data['trackingDate'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['platform'] === null) {
            $invalidProperties[] = "'platform' can't be null";
        }
        if ($this->container['trackingEvent'] === null) {
            $invalidProperties[] = "'trackingEvent' can't be null";
        }
        if ($this->container['sessionId'] === null) {
            $invalidProperties[] = "'sessionId' can't be null";
        }
        if ($this->container['created'] === null) {
            $invalidProperties[] = "'created' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets customerId
     *
     * @return string|null
     */
    public function getCustomerId()
    {
        return $this->container['customerId'];
    }

    /**
     * Sets customerId
     *
     * @param string|null $customerId customerId
     *
     * @return $this
     */
    public function setCustomerId($customerId)
    {
        $this->container['customerId'] = $customerId;

        return $this;
    }

    /**
     * Gets clientIP
     *
     * @return string|null
     */
    public function getClientIP()
    {
        return $this->container['clientIP'];
    }

    /**
     * Sets clientIP
     *
     * @param string|null $clientIP clientIP
     *
     * @return $this
     */
    public function setClientIP($clientIP)
    {
        $this->container['clientIP'] = $clientIP;

        return $this;
    }

    /**
     * Gets platform
     *
     * @return string
     */
    public function getPlatform()
    {
        return $this->container['platform'];
    }

    /**
     * Sets platform
     *
     * @param string $platform platform
     *
     * @return $this
     */
    public function setPlatform($platform)
    {
        $this->container['platform'] = $platform;

        return $this;
    }

    /**
     * Gets docDatabase
     *
     * @return string|null
     */
    public function getDocDatabase()
    {
        return $this->container['docDatabase'];
    }

    /**
     * Sets docDatabase
     *
     * @param string|null $docDatabase docDatabase
     *
     * @return $this
     */
    public function setDocDatabase($docDatabase)
    {
        $this->container['docDatabase'] = $docDatabase;

        return $this;
    }

    /**
     * Gets trackingEvent
     *
     * @return string
     */
    public function getTrackingEvent()
    {
        return $this->container['trackingEvent'];
    }

    /**
     * Sets trackingEvent
     *
     * @param string $trackingEvent trackingEvent
     *
     * @return $this
     */
    public function setTrackingEvent($trackingEvent)
    {
        $this->container['trackingEvent'] = $trackingEvent;

        return $this;
    }

    /**
     * Gets documentId
     *
     * @return string|null
     */
    public function getDocumentId()
    {
        return $this->container['documentId'];
    }

    /**
     * Sets documentId
     *
     * @param string|null $documentId documentId
     *
     * @return $this
     */
    public function setDocumentId($documentId)
    {
        $this->container['documentId'] = $documentId;

        return $this;
    }

    /**
     * Gets parentId
     *
     * @return string|null
     */
    public function getParentId()
    {
        return $this->container['parentId'];
    }

    /**
     * Sets parentId
     *
     * @param string|null $parentId parentId
     *
     * @return $this
     */
    public function setParentId($parentId)
    {
        $this->container['parentId'] = $parentId;

        return $this;
    }

    /**
     * Gets documentUrl
     *
     * @return string|null
     */
    public function getDocumentUrl()
    {
        return $this->container['documentUrl'];
    }

    /**
     * Sets documentUrl
     *
     * @param string|null $documentUrl documentUrl
     *
     * @return $this
     */
    public function setDocumentUrl($documentUrl)
    {
        $this->container['documentUrl'] = $documentUrl;

        return $this;
    }

    /**
     * Gets documentTitle
     *
     * @return string|null
     */
    public function getDocumentTitle()
    {
        return $this->container['documentTitle'];
    }

    /**
     * Sets documentTitle
     *
     * @param string|null $documentTitle documentTitle
     *
     * @return $this
     */
    public function setDocumentTitle($documentTitle)
    {
        $this->container['documentTitle'] = $documentTitle;

        return $this;
    }

    /**
     * Gets parentTitle
     *
     * @return string|null
     */
    public function getParentTitle()
    {
        return $this->container['parentTitle'];
    }

    /**
     * Sets parentTitle
     *
     * @param string|null $parentTitle parentTitle
     *
     * @return $this
     */
    public function setParentTitle($parentTitle)
    {
        $this->container['parentTitle'] = $parentTitle;

        return $this;
    }

    /**
     * Gets chapter
     *
     * @return string|null
     */
    public function getChapter()
    {
        return $this->container['chapter'];
    }

    /**
     * Sets chapter
     *
     * @param string|null $chapter chapter
     *
     * @return $this
     */
    public function setChapter($chapter)
    {
        $this->container['chapter'] = $chapter;

        return $this;
    }

    /**
     * Gets author
     *
     * @return string|null
     */
    public function getAuthor()
    {
        return $this->container['author'];
    }

    /**
     * Sets author
     *
     * @param string|null $author author
     *
     * @return $this
     */
    public function setAuthor($author)
    {
        $this->container['author'] = $author;

        return $this;
    }

    /**
     * Gets publisher
     *
     * @return string|null
     */
    public function getPublisher()
    {
        return $this->container['publisher'];
    }

    /**
     * Sets publisher
     *
     * @param string|null $publisher publisher
     *
     * @return $this
     */
    public function setPublisher($publisher)
    {
        $this->container['publisher'] = $publisher;

        return $this;
    }

    /**
     * Gets issnPrint
     *
     * @return string|null
     */
    public function getIssnPrint()
    {
        return $this->container['issnPrint'];
    }

    /**
     * Sets issnPrint
     *
     * @param string|null $issnPrint Print International Standard Serial Number
     *
     * @return $this
     */
    public function setIssnPrint($issnPrint)
    {
        $this->container['issnPrint'] = $issnPrint;

        return $this;
    }

    /**
     * Gets issnOnline
     *
     * @return string|null
     */
    public function getIssnOnline()
    {
        return $this->container['issnOnline'];
    }

    /**
     * Sets issnOnline
     *
     * @param string|null $issnOnline Online International Standard Serial Number
     *
     * @return $this
     */
    public function setIssnOnline($issnOnline)
    {
        $this->container['issnOnline'] = $issnOnline;

        return $this;
    }

    /**
     * Gets isbn
     *
     * @return string|null
     */
    public function getIsbn()
    {
        return $this->container['isbn'];
    }

    /**
     * Sets isbn
     *
     * @param string|null $isbn International Standard Book Number
     *
     * @return $this
     */
    public function setIsbn($isbn)
    {
        $this->container['isbn'] = $isbn;

        return $this;
    }

    /**
     * Gets isan
     *
     * @return string|null
     */
    public function getIsan()
    {
        return $this->container['isan'];
    }

    /**
     * Sets isan
     *
     * @param string|null $isan International Standard Audiovisual Number
     *
     * @return $this
     */
    public function setIsan($isan)
    {
        $this->container['isan'] = $isan;

        return $this;
    }

    /**
     * Gets ismn
     *
     * @return string|null
     */
    public function getIsmn()
    {
        return $this->container['ismn'];
    }

    /**
     * Sets ismn
     *
     * @param string|null $ismn International Standard Music Number
     *
     * @return $this
     */
    public function setIsmn($ismn)
    {
        $this->container['ismn'] = $ismn;

        return $this;
    }

    /**
     * Gets isrc
     *
     * @return string|null
     */
    public function getIsrc()
    {
        return $this->container['isrc'];
    }

    /**
     * Sets isrc
     *
     * @param string|null $isrc The International Standard Recording Code
     *
     * @return $this
     */
    public function setIsrc($isrc)
    {
        $this->container['isrc'] = $isrc;

        return $this;
    }

    /**
     * Gets istc
     *
     * @return string|null
     */
    public function getIstc()
    {
        return $this->container['istc'];
    }

    /**
     * Sets istc
     *
     * @param string|null $istc International Standard Text Code
     *
     * @return $this
     */
    public function setIstc($istc)
    {
        $this->container['istc'] = $istc;

        return $this;
    }

    /**
     * Gets doi
     *
     * @return string|null
     */
    public function getDoi()
    {
        return $this->container['doi'];
    }

    /**
     * Sets doi
     *
     * @param string|null $doi Digital Object Identifier
     *
     * @return $this
     */
    public function setDoi($doi)
    {
        $this->container['doi'] = $doi;

        return $this;
    }

    /**
     * Gets proprietaryId
     *
     * @return string|null
     */
    public function getProprietaryId()
    {
        return $this->container['proprietaryId'];
    }

    /**
     * Sets proprietaryId
     *
     * @param string|null $proprietaryId proprietaryId
     *
     * @return $this
     */
    public function setProprietaryId($proprietaryId)
    {
        $this->container['proprietaryId'] = $proprietaryId;

        return $this;
    }

    /**
     * Gets accessMethod
     *
     * @return string|null
     */
    public function getAccessMethod()
    {
        return $this->container['accessMethod'];
    }

    /**
     * Sets accessMethod
     *
     * @param string|null $accessMethod accessMethod
     *
     * @return $this
     */
    public function setAccessMethod($accessMethod)
    {
        $this->container['accessMethod'] = $accessMethod;

        return $this;
    }

    /**
     * Gets accessType
     *
     * @return string|null
     */
    public function getAccessType()
    {
        return $this->container['accessType'];
    }

    /**
     * Sets accessType
     *
     * @param string|null $accessType accessType
     *
     * @return $this
     */
    public function setAccessType($accessType)
    {
        $this->container['accessType'] = $accessType;

        return $this;
    }

    /**
     * Gets dataType
     *
     * @return string|null
     */
    public function getDataType()
    {
        return $this->container['dataType'];
    }

    /**
     * Sets dataType
     *
     * @param string|null $dataType dataType
     *
     * @return $this
     */
    public function setDataType($dataType)
    {
        $this->container['dataType'] = $dataType;

        return $this;
    }

    /**
     * Gets sectionType
     *
     * @return string|null
     */
    public function getSectionType()
    {
        return $this->container['sectionType'];
    }

    /**
     * Sets sectionType
     *
     * @param string|null $sectionType sectionType
     *
     * @return $this
     */
    public function setSectionType($sectionType)
    {
        $this->container['sectionType'] = $sectionType;

        return $this;
    }

    /**
     * Gets yop
     *
     * @return string|null
     */
    public function getYop()
    {
        return $this->container['yop'];
    }

    /**
     * Sets yop
     *
     * @param string|null $yop yop
     *
     * @return $this
     */
    public function setYop($yop)
    {
        $this->container['yop'] = $yop;

        return $this;
    }

    /**
     * Gets sessionId
     *
     * @return string
     */
    public function getSessionId()
    {
        return $this->container['sessionId'];
    }

    /**
     * Sets sessionId
     *
     * @param string $sessionId sessionId
     *
     * @return $this
     */
    public function setSessionId($sessionId)
    {
        $this->container['sessionId'] = $sessionId;

        return $this;
    }

    /**
     * Gets created
     *
     * @return int
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param int $created created
     *
     * @return $this
     */
    public function setCreated($created)
    {
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets trackingDate
     *
     * @return \DateTime|null
     */
    public function getTrackingDate()
    {
        return $this->container['trackingDate'];
    }

    /**
     * Sets trackingDate
     *
     * @param \DateTime|null $trackingDate trackingDate
     *
     * @return $this
     */
    public function setTrackingDate($trackingDate)
    {
        $this->container['trackingDate'] = $trackingDate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


