<?php
/**
 * TrackingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Subugoe\CounterClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 5
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Subugoe\CounterClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TrackingTest Class Doc Comment
 *
 * @category    Class
 * @description
 * @package     Subugoe\CounterClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TrackingTest extends TestCase
{

}
