<?php
/**
 * TrackingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Subugoe\CounterClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Subugoe\CounterClient;

/**
 * TrackingTest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Subugoe\CounterClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TrackingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Tracking"
     */
    public function testTracking()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "apiKey"
     */
    public function testPropertyApiKey()
    {
    }

    /**
     * Test attribute "customerId"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "institutionName"
     */
    public function testPropertyInstitutionName()
    {
    }

    /**
     * Test attribute "institutionId"
     */
    public function testPropertyInstitutionId()
    {
    }

    /**
     * Test attribute "clientIP"
     */
    public function testPropertyClientIP()
    {
    }

    /**
     * Test attribute "userAgent"
     */
    public function testPropertyUserAgent()
    {
    }

    /**
     * Test attribute "platform"
     */
    public function testPropertyPlatform()
    {
    }

    /**
     * Test attribute "docDatabase"
     */
    public function testPropertyDocDatabase()
    {
    }

    /**
     * Test attribute "trackingEvent"
     */
    public function testPropertyTrackingEvent()
    {
    }

    /**
     * Test attribute "documentId"
     */
    public function testPropertyDocumentId()
    {
    }

    /**
     * Test attribute "parentId"
     */
    public function testPropertyParentId()
    {
    }

    /**
     * Test attribute "documentUrl"
     */
    public function testPropertyDocumentUrl()
    {
    }

    /**
     * Test attribute "documentTitle"
     */
    public function testPropertyDocumentTitle()
    {
    }

    /**
     * Test attribute "parentTitle"
     */
    public function testPropertyParentTitle()
    {
    }

    /**
     * Test attribute "chapter"
     */
    public function testPropertyChapter()
    {
    }

    /**
     * Test attribute "author"
     */
    public function testPropertyAuthor()
    {
    }

    /**
     * Test attribute "publisher"
     */
    public function testPropertyPublisher()
    {
    }

    /**
     * Test attribute "publisherId"
     */
    public function testPropertyPublisherId()
    {
    }

    /**
     * Test attribute "issnPrint"
     */
    public function testPropertyIssnPrint()
    {
    }

    /**
     * Test attribute "issnOnline"
     */
    public function testPropertyIssnOnline()
    {
    }

    /**
     * Test attribute "isbn"
     */
    public function testPropertyIsbn()
    {
    }

    /**
     * Test attribute "isan"
     */
    public function testPropertyIsan()
    {
    }

    /**
     * Test attribute "ismn"
     */
    public function testPropertyIsmn()
    {
    }

    /**
     * Test attribute "isrc"
     */
    public function testPropertyIsrc()
    {
    }

    /**
     * Test attribute "istc"
     */
    public function testPropertyIstc()
    {
    }

    /**
     * Test attribute "doi"
     */
    public function testPropertyDoi()
    {
    }

    /**
     * Test attribute "proprietaryId"
     */
    public function testPropertyProprietaryId()
    {
    }

    /**
     * Test attribute "accessMethod"
     */
    public function testPropertyAccessMethod()
    {
    }

    /**
     * Test attribute "accessType"
     */
    public function testPropertyAccessType()
    {
    }

    /**
     * Test attribute "dataType"
     */
    public function testPropertyDataType()
    {
    }

    /**
     * Test attribute "sectionType"
     */
    public function testPropertySectionType()
    {
    }

    /**
     * Test attribute "yop"
     */
    public function testPropertyYop()
    {
    }

    /**
     * Test attribute "sessionId"
     */
    public function testPropertySessionId()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "trackingDate"
     */
    public function testPropertyTrackingDate()
    {
    }
}
