<?php
/**
 * TrackingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Subugoe\CounterClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 5
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Subugoe\CounterClient\Test\Api;

use PHPUnit\Framework\TestCase;
use \Subugoe\CounterClient\Configuration;
use \Subugoe\CounterClient\ApiException;
use \Subugoe\CounterClient\ObjectSerializer;

/**
 * TrackingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Subugoe\CounterClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TrackingApiTest extends TestCase
{



}
